version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: spotify_ingestion_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/spotify_metadata_etl_project
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    # command: poetry run pytest --cov=spotify_metadata_etl_project tests/ --cov-report=xml
    depends_on:
      - postgres
