name: Lint Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_check:
    name: Run lint check in Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and test
        run: |
          docker compose build
          docker compose run --rm app sh -c "poetry run ruff check . && poetry run isort --check ."